package ifx.rpc.typescript.ksp

internal class TypeScriptRenderer {
    fun render(service: ServiceModel): String {
        val names = allocateNames(service)
        return buildString {
            appendLine("// Generated by ifx.rpc.typescript.ksp. Do not edit.")
            appendLine()
            appendLine("import {")
            appendLine("  RSocketBinding as __IfxRSocketBinding,")
            appendLine("  type IfxBinding as __IfxBinding,")
            appendLine("  type RSocketBindingOptions as __IfxRSocketBindingOptions,")
            appendLine("} from \"@ifx/rpc-client\";")
            appendLine()
            appendLine("export const ${identifier(service.name)}Address = ${stringLiteral(service.address)};")
            appendLine()
            appendLine("export namespace ${identifier(service.name)} {")
            service.operations.forEachIndexed { index, operation ->
                appendLine("  export type ${identifier(operation.typeName)}Request = ${renderType(operation.request, names)};")
                appendLine("  export type ${identifier(operation.typeName)}Response = ${renderType(operation.response, names)};")
                if (index != service.operations.lastIndex) appendLine()
            }
            appendLine("}")
            appendLine()
            appendLine("export interface ${identifier(service.name)} {")
            service.operations.forEach { operation ->
                val parameter = operation.parameterName?.let {
                    "${identifier(it)}${if (operation.requestOptional) "?" else ""}: ${identifier(service.name)}.${identifier(operation.typeName)}Request"
                }.orEmpty()
                val response = "${identifier(service.name)}.${identifier(operation.typeName)}Response"
                val result = when (operation.interaction) {
                    Interaction.REQUEST_STREAM -> "AsyncIterable<$response>"
                    Interaction.FIRE_AND_FORGET, Interaction.REQUEST_RESPONSE -> "Promise<$response>"
                }
                appendLine("  ${propertyName(operation.name)}($parameter): $result;")
            }
            appendLine("}")

            appendLine()
            appendLine("export class ${identifier(service.name)}Client implements ${identifier(service.name)} {")
            appendLine("  static async connect(")
            appendLine("    baseUrl: string,")
            appendLine("    options: Omit<__IfxRSocketBindingOptions, \"url\"> = {},")
            appendLine("  ): Promise<${identifier(service.name)}Client> {")
            appendLine("    const url = __IfxRSocketBinding.serviceUrl(baseUrl, ${identifier(service.name)}Address);")
            appendLine("    return new ${identifier(service.name)}Client(await __IfxRSocketBinding.connect({ ...options, url }));")
            appendLine("  }")
            appendLine()
            appendLine("  constructor(private readonly binding: __IfxBinding) {}")
            appendLine()
            service.operations.forEachIndexed { index, operation ->
                append(renderClientMethod(service, operation))
                if (index != service.operations.lastIndex) appendLine()
            }
            appendLine()
            appendLine("  close(): void {")
            appendLine("    this.binding.close();")
            appendLine("  }")
            appendLine("}")

            service.declarations.forEach { declaration ->
                appendLine()
                append(renderDeclaration(declaration, names))
            }
        }
    }

    private fun renderClientMethod(service: ServiceModel, operation: OperationModel): String {
        val serviceName = identifier(service.name)
        val parameter = operation.parameterName?.let {
            "${identifier(it)}: $serviceName.${identifier(operation.typeName)}Request"
        }.orEmpty()
        val argument = operation.parameterName?.let { ", ${identifier(it)}" }.orEmpty()
        val response = "$serviceName.${identifier(operation.typeName)}Response"
        val invocation = when (operation.interaction) {
            Interaction.FIRE_AND_FORGET -> "this.binding.fireAndForget(${stringLiteral(operation.route)}$argument)"
            Interaction.REQUEST_RESPONSE -> "this.binding.requestResponse<$response>(${stringLiteral(operation.route)}$argument)"
            Interaction.REQUEST_STREAM -> "this.binding.requestStream<$response>(${stringLiteral(operation.route)}$argument)"
        }
        val result = when (operation.interaction) {
            Interaction.REQUEST_STREAM -> "AsyncIterable<$response>"
            Interaction.FIRE_AND_FORGET, Interaction.REQUEST_RESPONSE -> "Promise<$response>"
        }
        return buildString {
            appendLine("  ${propertyName(operation.name)}($parameter): $result {")
            appendLine("    return $invocation;")
            appendLine("  }")
        }
    }

    private fun renderDeclaration(declaration: TypeDeclaration, names: Map<String, String>): String {
        val name = names.getValue(declaration.qualifiedName)
        val parameters = declaration.typeParameters.joinToString(prefix = "<", postfix = ">") { identifier(it) }
            .takeIf { declaration.typeParameters.isNotEmpty() }.orEmpty()
        return when (declaration) {
            is TypeDeclaration.ObjectType -> buildString {
                appendLine("export interface $name$parameters {")
                declaration.properties.forEach { property ->
                    appendLine("  readonly ${propertyName(property.name)}${if (property.optional) "?" else ""}: ${renderType(property.type, names)};")
                }
                appendLine("}")
            }
            is TypeDeclaration.StringUnion ->
                "export type $name = ${declaration.values.joinToString(" | ") { stringLiteral(it) }};\n"
            is TypeDeclaration.SealedUnion -> {
                val variants = declaration.variants.joinToString("\n  | ") { variant ->
                    "({ readonly ${propertyName(declaration.discriminator)}: ${stringLiteral(variant.serialName)} } & ${renderType(variant.type, names)})"
                }
                "export type $name$parameters =\n  | $variants;\n"
            }
            is TypeDeclaration.Alias ->
                "export type $name$parameters = ${renderType(declaration.target, names)};\n"
        }
    }

    private fun renderType(type: TypeRef, names: Map<String, String>): String = when (type) {
        TypeRef.StringType -> "string"
        TypeRef.NumberType -> "number"
        TypeRef.BooleanType -> "boolean"
        TypeRef.VoidType -> "void"
        is TypeRef.TypeParameter -> identifier(type.name)
        is TypeRef.Named -> names.getValue(type.qualifiedName) + type.arguments
            .joinToString(prefix = "<", postfix = ">") { renderType(it, names) }
            .takeIf { type.arguments.isNotEmpty() }.orEmpty()
        is TypeRef.ArrayType -> "ReadonlyArray<${renderType(type.element, names)}>"
        is TypeRef.RecordType -> "Readonly<Record<string, ${renderType(type.value, names)}>>"
        is TypeRef.Nullable -> "${renderType(type.value, names)} | null"
    }

    private fun allocateNames(service: ServiceModel): Map<String, String> {
        val bySimpleName = service.declarations.groupBy { it.qualifiedName.substringAfterLast('.') }
        return service.declarations.associate { declaration ->
            val simpleName = declaration.qualifiedName.substringAfterLast('.')
            val allocated = if (bySimpleName.getValue(simpleName).size == 1 && simpleName != service.name) {
                simpleName
            } else {
                declaration.qualifiedName.replace(Regex("[^A-Za-z0-9_$]"), "_")
            }
            declaration.qualifiedName to identifier(allocated)
        }
    }

    private fun propertyName(value: String): String =
        if (IDENTIFIER.matches(value) && value !in RESERVED_WORDS) value else stringLiteral(value)

    private fun identifier(value: String): String {
        val sanitized = value.replace(Regex("[^A-Za-z0-9_$]"), "_")
        val prefixed = if (sanitized.firstOrNull()?.let { it.isLetter() || it == '_' || it == '$' } == true) sanitized else "_$sanitized"
        return if (prefixed in RESERVED_WORDS) "_${prefixed}" else prefixed
    }

    private fun stringLiteral(value: String): String = buildString {
        append('"')
        value.forEach { character ->
            when (character) {
                '\\' -> append("\\\\")
                '"' -> append("\\\"")
                '\n' -> append("\\n")
                '\r' -> append("\\r")
                '\t' -> append("\\t")
                else -> append(character)
            }
        }
        append('"')
    }

    private companion object {
        val IDENTIFIER = Regex("[A-Za-z_$][A-Za-z0-9_$]*")
        val RESERVED_WORDS = setOf(
            "break", "case", "catch", "class", "const", "continue", "debugger", "default", "delete", "do",
            "else", "enum", "export", "extends", "false", "finally", "for", "function", "if", "import", "in",
            "instanceof", "interface", "let", "new", "null", "package", "private", "protected", "public", "return",
            "static", "super", "switch", "this", "throw", "true", "try", "typeof", "var", "void", "while",
            "with", "yield",
        )
    }
}
