package ifx.rpc.typescript.ksp

import ifx.rpc.schema.ksp.Interaction
import ifx.rpc.schema.ksp.OperationModel
import ifx.rpc.schema.ksp.ServiceKind
import ifx.rpc.schema.ksp.ServiceModel
import ifx.rpc.schema.ksp.TypeDeclaration
import ifx.rpc.schema.ksp.TypeRef

internal class TypeScriptRenderer {
    fun render(service: ServiceModel): String {
        val names = allocateNames(service)
        val operationAliases = operationAliases(service)
        val bridgedOperationAliases = operationAliases.filter { alias ->
            referencesName(alias.type, alias.name, names)
        }
        return buildString {
            appendLine("// Generated by ifx.rpc.typescript.ksp. Do not edit.")
            appendLine()
            appendLine("import {")
            appendLine("  type IfxBinding as __IfxBinding,")
            appendLine("  type IfxServiceDescription as __IfxServiceDescription,")
            appendLine("} from \"@carbide-ifx/rpc-sdk\";")
            appendLine()
            appendLine("export const ${identifier(service.name)}Address = ${stringLiteral(service.address)};")
            appendLine()
            append(renderDescription(service))
            appendLine()
            bridgedOperationAliases.forEach { alias ->
                appendLine("type ${operationBridgeName(service, alias.name)} = ${renderType(alias.type, names)};")
            }
            if (bridgedOperationAliases.isNotEmpty()) appendLine()
            appendLine("export namespace ${identifier(service.name)} {")
            service.operations.forEachIndexed { index, operation ->
                appendLine(renderOperationAlias(service, operationAliases[index * 2], names))
                appendLine(renderOperationAlias(service, operationAliases[index * 2 + 1], names))
                if (index != service.operations.lastIndex) appendLine()
            }
            appendLine("}")
            appendLine()
            appendLine("export interface ${identifier(service.name)} {")
            service.operations.forEach { operation ->
                val parameter = operation.parameterName?.let {
                    "${identifier(it)}: ${identifier(service.name)}.${operation.typeName()}Request"
                }.orEmpty()
                val response = "${identifier(service.name)}.${operation.typeName()}Response"
                val result = when (operation.interaction) {
                    Interaction.REQUEST_STREAM -> "AsyncIterable<$response>"
                    Interaction.FIRE_AND_FORGET, Interaction.REQUEST_RESPONSE -> "Promise<$response>"
                }
                appendLine("  ${propertyName(operation.name)}($parameter): $result;")
            }
            appendLine("}")

            appendLine()
            appendLine("export class ${identifier(service.name)}Sdk implements ${identifier(service.name)} {")
            appendLine("  static readonly address = ${identifier(service.name)}Address;")
            appendLine()
            appendLine("  constructor(private readonly binding: __IfxBinding) {}")
            appendLine()
            service.operations.forEachIndexed { index, operation ->
                append(renderSdkMethod(service, operation))
                if (index != service.operations.lastIndex) appendLine()
            }
            appendLine()
            appendLine("  close(): void {")
            appendLine("    this.binding.close();")
            appendLine("  }")
            appendLine("}")

            service.declarations.forEach { declaration ->
                appendLine()
                append(renderDeclaration(declaration, names))
            }
        }
    }

    private fun renderDescription(service: ServiceModel): String = buildString {
        appendLine("export const ${identifier(service.name)}Description = {")
        appendLine("  name: ${stringLiteral(service.name)},")
        appendLine("  address: ${identifier(service.name)}Address,")
        appendLine("  kind: ${stringLiteral(if (service.kind == ServiceKind.UTILITY) "utility" else "service")},")
        appendLine("  operations: [")
        service.operations.forEach { operation ->
            val interaction = when (operation.interaction) {
                Interaction.FIRE_AND_FORGET -> "fireAndForget"
                Interaction.REQUEST_RESPONSE -> "requestResponse"
                Interaction.REQUEST_STREAM -> "requestStream"
            }
            appendLine("    {")
            appendLine("      name: ${stringLiteral(operation.name)},")
            appendLine("      route: ${stringLiteral(operation.route)},")
            appendLine("      parameterName: ${operation.parameterName?.let(::stringLiteral) ?: "null"},")
            appendLine("      request: ${renderTypeReference(operation.request)},")
            appendLine("      response: ${renderTypeReference(operation.response)},")
            appendLine("      interaction: ${stringLiteral(interaction)},")
            appendLine("    },")
        }
        appendLine("  ],")
        appendLine("  types: [")
        service.declarations.forEach { declaration ->
            appendLine("    ${renderTypeDescription(declaration)},")
        }
        appendLine("  ],")
        appendLine("} as const satisfies __IfxServiceDescription;")
    }

    private fun renderTypeReference(type: TypeRef): String = when (type) {
        TypeRef.StringType -> "{ type: \"string\" }"
        TypeRef.NumberType -> "{ type: \"number\" }"
        TypeRef.BooleanType -> "{ type: \"boolean\" }"
        TypeRef.VoidType -> "{ type: \"void\" }"
        is TypeRef.TypeParameter -> "{ type: \"parameter\", name: ${stringLiteral(type.name)} }"
        is TypeRef.Named -> "{ type: \"named\", name: ${stringLiteral(type.qualifiedName)}, arguments: [${type.arguments.joinToString { renderTypeReference(it) }}] }"
        is TypeRef.ArrayType -> "{ type: \"array\", element: ${renderTypeReference(type.element)} }"
        is TypeRef.RecordType -> "{ type: \"record\", value: ${renderTypeReference(type.value)} }"
        is TypeRef.Nullable -> "{ type: \"nullable\", value: ${renderTypeReference(type.value)} }"
    }

    private fun renderTypeDescription(declaration: TypeDeclaration): String = when (declaration) {
        is TypeDeclaration.ObjectType -> "{" +
            " type: \"object\", name: ${stringLiteral(declaration.qualifiedName)}," +
            " typeParameters: [${declaration.typeParameters.joinToString { stringLiteral(it) }}]," +
            " properties: [${declaration.properties.joinToString { property ->
                "{ name: ${stringLiteral(property.name)}, type: ${renderTypeReference(property.type)}, optional: ${property.optional} }"
            }}] }"
        is TypeDeclaration.StringUnion -> "{" +
            " type: \"stringUnion\", name: ${stringLiteral(declaration.qualifiedName)}," +
            " typeParameters: [${declaration.typeParameters.joinToString { stringLiteral(it) }}]," +
            " values: [${declaration.values.joinToString { stringLiteral(it) }}] }"
        is TypeDeclaration.SealedUnion -> "{" +
            " type: \"sealedUnion\", name: ${stringLiteral(declaration.qualifiedName)}," +
            " typeParameters: [${declaration.typeParameters.joinToString { stringLiteral(it) }}]," +
            " discriminator: ${stringLiteral(declaration.discriminator)}," +
            " variants: [${declaration.variants.joinToString { variant ->
                "{ serialName: ${stringLiteral(variant.serialName)}, type: ${renderTypeReference(variant.type)} }"
            }}] }"
        is TypeDeclaration.Alias -> "{" +
            " type: \"alias\", name: ${stringLiteral(declaration.qualifiedName)}," +
            " typeParameters: [${declaration.typeParameters.joinToString { stringLiteral(it) }}]," +
            " target: ${renderTypeReference(declaration.target)} }"
    }

    private fun renderSdkMethod(service: ServiceModel, operation: OperationModel): String {
        val serviceName = identifier(service.name)
        val parameter = operation.parameterName?.let {
            "${identifier(it)}: $serviceName.${operation.typeName()}Request"
        }.orEmpty()
        val argument = operation.parameterName?.let { ", ${identifier(it)}" }.orEmpty()
        val response = "$serviceName.${operation.typeName()}Response"
        val invocation = when (operation.interaction) {
            Interaction.FIRE_AND_FORGET -> "this.binding.fireAndForget(${stringLiteral(operation.route)}$argument)"
            Interaction.REQUEST_RESPONSE -> "this.binding.requestResponse<$response>(${stringLiteral(operation.route)}$argument)"
            Interaction.REQUEST_STREAM -> "this.binding.requestStream<$response>(${stringLiteral(operation.route)}$argument)"
        }
        val result = when (operation.interaction) {
            Interaction.REQUEST_STREAM -> "AsyncIterable<$response>"
            Interaction.FIRE_AND_FORGET, Interaction.REQUEST_RESPONSE -> "Promise<$response>"
        }
        return buildString {
            val awaitsVoidResponse = operation.interaction == Interaction.REQUEST_RESPONSE &&
                operation.response == TypeRef.VoidType
            appendLine("  ${if (awaitsVoidResponse) "async " else ""}${propertyName(operation.name)}($parameter): $result {")
            if (awaitsVoidResponse) {
                appendLine("    await $invocation;")
            } else {
                appendLine("    return $invocation;")
            }
            appendLine("  }")
        }
    }

    private fun renderDeclaration(declaration: TypeDeclaration, names: Map<String, String>): String {
        val name = names.getValue(declaration.qualifiedName)
        val parameters = declaration.typeParameters.joinToString(prefix = "<", postfix = ">") { identifier(it) }
            .takeIf { declaration.typeParameters.isNotEmpty() }.orEmpty()
        return when (declaration) {
            is TypeDeclaration.ObjectType -> buildString {
                appendLine("export interface $name$parameters {")
                declaration.properties.forEach { property ->
                    appendLine("  readonly ${propertyName(property.name)}${if (property.optional) "?" else ""}: ${renderType(property.type, names)};")
                }
                appendLine("}")
            }
            is TypeDeclaration.StringUnion ->
                "export type $name = ${declaration.values.joinToString(" | ") { stringLiteral(it) }};\n"
            is TypeDeclaration.SealedUnion -> {
                val variants = declaration.variants.joinToString("\n  | ") { variant ->
                    "({ readonly ${propertyName(declaration.discriminator)}: ${stringLiteral(variant.serialName)} } & ${renderType(variant.type, names)})"
                }
                "export type $name$parameters =\n  | $variants;\n"
            }
            is TypeDeclaration.Alias ->
                "export type $name$parameters = ${renderType(declaration.target, names)};\n"
        }
    }

    private fun renderOperationAlias(
        service: ServiceModel,
        alias: OperationAlias,
        names: Map<String, String>,
    ): String {
        val target = if (referencesName(alias.type, alias.name, names)) {
            operationBridgeName(service, alias.name)
        } else {
            renderType(alias.type, names)
        }
        return "  export type ${alias.name} = $target;"
    }

    private fun operationAliases(service: ServiceModel): List<OperationAlias> =
        service.operations.flatMap { operation ->
            listOf(
                OperationAlias("${operation.typeName()}Request", operation.request),
                OperationAlias("${operation.typeName()}Response", operation.response),
            )
        }

    private fun operationBridgeName(service: ServiceModel, aliasName: String): String =
        identifier("__${service.name}_$aliasName")

    private fun referencesName(type: TypeRef, name: String, names: Map<String, String>): Boolean = when (type) {
        TypeRef.StringType, TypeRef.NumberType, TypeRef.BooleanType, TypeRef.VoidType -> false
        is TypeRef.TypeParameter -> identifier(type.name) == name
        is TypeRef.Named -> names.getValue(type.qualifiedName) == name ||
            type.arguments.any { referencesName(it, name, names) }
        is TypeRef.ArrayType -> referencesName(type.element, name, names)
        is TypeRef.RecordType -> referencesName(type.value, name, names)
        is TypeRef.Nullable -> referencesName(type.value, name, names)
    }

    private fun renderType(type: TypeRef, names: Map<String, String>): String = when (type) {
        TypeRef.StringType -> "string"
        TypeRef.NumberType -> "number"
        TypeRef.BooleanType -> "boolean"
        TypeRef.VoidType -> "void"
        is TypeRef.TypeParameter -> identifier(type.name)
        is TypeRef.Named -> names.getValue(type.qualifiedName) + type.arguments
            .joinToString(prefix = "<", postfix = ">") { renderType(it, names) }
            .takeIf { type.arguments.isNotEmpty() }.orEmpty()
        is TypeRef.ArrayType -> "ReadonlyArray<${renderType(type.element, names)}>"
        is TypeRef.RecordType -> "Readonly<Record<string, ${renderType(type.value, names)}>>"
        is TypeRef.Nullable -> "${renderType(type.value, names)} | null"
    }

    private fun allocateNames(service: ServiceModel): Map<String, String> {
        val bySimpleName = service.declarations.groupBy { it.qualifiedName.substringAfterLast('.') }
        val generatedNames = buildSet {
            add(service.name)
            add("${service.name}Address")
            add("${service.name}Sdk")
            add("${service.name}Description")
            operationAliases(service).forEach { alias ->
                add(operationBridgeName(service, alias.name))
            }
        }
        return service.declarations.associate { declaration ->
            val simpleName = declaration.qualifiedName.substringAfterLast('.')
            val allocated = if (bySimpleName.getValue(simpleName).size == 1 && simpleName !in generatedNames) {
                simpleName
            } else {
                declaration.qualifiedName.replace(Regex("[^A-Za-z0-9_$]"), "_")
            }
            declaration.qualifiedName to identifier(allocated)
        }
    }

    private fun propertyName(value: String): String =
        if (IDENTIFIER.matches(value) && value !in RESERVED_WORDS) value else stringLiteral(value)

    private fun identifier(value: String): String {
        val sanitized = value.replace(Regex("[^A-Za-z0-9_$]"), "_")
        val prefixed = if (sanitized.firstOrNull()?.let { it.isLetter() || it == '_' || it == '$' } == true) sanitized else "_$sanitized"
        return if (prefixed in RESERVED_WORDS) "_${prefixed}" else prefixed
    }

    private fun stringLiteral(value: String): String = buildString {
        append('"')
        value.forEach { character ->
            when (character) {
                '\\' -> append("\\\\")
                '"' -> append("\\\"")
                '\n' -> append("\\n")
                '\r' -> append("\\r")
                '\t' -> append("\\t")
                else -> append(character)
            }
        }
        append('"')
    }

    private companion object {
        val IDENTIFIER = Regex("[A-Za-z_$][A-Za-z0-9_$]*")
        val RESERVED_WORDS = setOf(
            "break", "case", "catch", "class", "const", "continue", "debugger", "default", "delete", "do",
            "else", "enum", "export", "extends", "false", "finally", "for", "function", "if", "import", "in",
            "instanceof", "interface", "let", "new", "null", "package", "private", "protected", "public", "return",
            "static", "super", "switch", "this", "throw", "true", "try", "typeof", "var", "void", "while",
            "with", "yield",
        )
    }

    private fun OperationModel.typeName(): String = identifier(name.replaceFirstChar { character ->
        if (character.isLowerCase()) character.titlecase() else character.toString()
    })

    private data class OperationAlias(
        val name: String,
        val type: TypeRef,
    )
}
