modules:
  - ifx.actuator
  - ifx.context
  - ifx.host
  - ifx.host.contract
  - ifx.logging
  - ifx.protocol.contract
  - ifx.protocol.jsonrpc
  - ifx.protocol.rsocket
  - ifx.proxy-factory.base
  - ifx.proxy-factory.contract
  - ifx.proxy-factory.jsonrpc
  - ifx.proxy-factory.rsocket
  - ifx.rpc.compiler-plugin
  - ifx.rpc.ksp
  - ifx.rpc.typescript.ksp
  - ifx.service
  - ifx.telemetry.otel
  - ifx.testing
  - test.test-system
  - utility.db
  - utility.stdlib
