rootProject.name = "ifx"
include(":context")
include(":host")
include(":naming")
include(":logging")
include(":proxy")
include(":service")
include(":transport")
include(":stdlib")
include(":test")
include(":protocol:contract")
include(":protocol:rsocket")
