package ifx.gateway.typescript

import ifx.gateway.contract.GatewayOperationProjection
import ifx.gateway.contract.GatewayProjection
import ifx.gateway.contract.GatewayServiceProjection
import ifx.protocol.contract.InteractionType
import ifx.protocol.contract.TypeDescription
import ifx.protocol.contract.TypeReference

/** Renders a protocol-neutral SDK for one immutable gateway projection. */
fun GatewayProjection.renderTypeScriptSdk(): String = GatewayTypeScriptRenderer(this).render()

private class GatewayTypeScriptRenderer(
    private val projection: GatewayProjection,
) {
    private val sdkName = projection.name.toPascalIdentifier()
    private val types = mergeTypes(projection)
    private val typeNames = allocateTypeNames(types)

    fun render(): String = buildString {
        appendLine("// Generated by ifx.gateway.typescript. Do not edit.")
        appendLine()
        appendLine("import { type IfxBinding as __IfxBinding } from \"@ifx/rpc-sdk\";")
        appendLine()
        appendLine("export const ${sdkName}Address = ${projection.address().quoted()};")
        appendLine()
        appendLine("export namespace $sdkName {")
        projection.services.forEach { service ->
            appendLine("  export interface ${service.name.toPascalIdentifier()} {")
            service.operations.forEach { operation ->
                appendLine("    ${operation.methodSignature()};")
            }
            appendLine("  }")
        }
        appendLine("}")
        appendLine()
        appendLine("export class ${sdkName}Sdk {")
        appendLine("  static readonly address = ${sdkName}Address;")
        projection.services.forEach { service ->
            appendLine("  readonly ${service.name.propertyName()}: $sdkName.${service.name.toPascalIdentifier()};")
        }
        appendLine()
        appendLine("  constructor(private readonly binding: __IfxBinding) {")
        projection.services.forEach { service -> append(service.assignment()) }
        appendLine("  }")
        appendLine()
        appendLine("  close(): void {")
        appendLine("    this.binding.close();")
        appendLine("  }")
        appendLine("}")
        types.forEach { type ->
            appendLine()
            append(type.declaration())
        }
    }

    private fun GatewayServiceProjection.assignment(): String = buildString {
        appendLine("    this.${name.propertyName()} = {")
        operations.forEach { operation ->
            val parameter = operation.parameterDeclaration()
            val argument = operation.argument()
            val invocation = when (operation.description.interaction) {
                InteractionType.FIRE_AND_FORGET -> "this.binding.fireAndForget(${"$name/${operation.name}".quoted()}$argument)"
                InteractionType.REQUEST_RESPONSE -> "this.binding.requestResponse<${operation.description.response.render()}>(${"$name/${operation.name}".quoted()}$argument)"
                InteractionType.REQUEST_STREAM -> "this.binding.requestStream<${operation.description.response.render()}>(${"$name/${operation.name}".quoted()}$argument)"
            }
            appendLine("      ${operation.name.propertyName()}: ($parameter) => $invocation,")
        }
        appendLine("    };")
    }

    private fun GatewayOperationProjection.methodSignature(): String =
        "${name.propertyName()}(${parameterDeclaration()}): ${resultType()}"

    private fun GatewayOperationProjection.parameterDeclaration(): String =
        description.parameterName?.let { "${it.identifier()}: ${description.request.render()}" }.orEmpty()

    private fun GatewayOperationProjection.argument(): String =
        description.parameterName?.let { ", ${it.identifier()}" }.orEmpty()

    private fun GatewayOperationProjection.resultType(): String = when (description.interaction) {
        InteractionType.REQUEST_STREAM -> "AsyncIterable<${description.response.render()}>"
        InteractionType.FIRE_AND_FORGET, InteractionType.REQUEST_RESPONSE ->
            "Promise<${description.response.render()}>"
    }

    private fun TypeReference.render(): String = when (this) {
        TypeReference.StringType -> "string"
        TypeReference.NumberType -> "number"
        TypeReference.BooleanType -> "boolean"
        TypeReference.VoidType -> "void"
        is TypeReference.Parameter -> name.identifier()
        is TypeReference.Named -> {
            val typeName = typeNames[name] ?: name.toTypeIdentifier()
            typeName + arguments
                .takeIf(List<TypeReference>::isNotEmpty)
                ?.joinToString(prefix = "<", postfix = ">") { argument -> argument.render() }
                .orEmpty()
        }
        is TypeReference.ArrayType -> "ReadonlyArray<${element.render()}>"
        is TypeReference.RecordType -> "Readonly<Record<string, ${value.render()}>>"
        is TypeReference.Nullable -> "${value.render()} | null"
    }

    private fun TypeDescription.declaration(): String = when (this) {
        is TypeDescription.ObjectType -> buildString {
            appendLine("export interface ${typeNames.getValue(name)}${typeParameters.parameters()} {")
            properties.forEach { property ->
                appendLine("  readonly ${property.name.propertyName()}${if (property.optional) "?" else ""}: ${property.type.render()};")
            }
            appendLine("}")
        }
        is TypeDescription.StringUnion ->
            "export type ${typeNames.getValue(name)} = ${values.joinToString(" | ") { it.quoted() }};\n"
        is TypeDescription.SealedUnion -> buildString {
            appendLine("export type ${typeNames.getValue(name)}${typeParameters.parameters()} =")
            variants.forEachIndexed { index, variant ->
                val prefix = if (index == 0) "  " else "  | "
                appendLine("$prefix({ readonly ${discriminator.propertyName()}: ${variant.serialName.quoted()} } & ${variant.type.render()})")
            }
            appendLine(";")
        }
        is TypeDescription.Alias ->
            "export type ${typeNames.getValue(name)}${typeParameters.parameters()} = ${target.render()};\n"
    }

    private fun List<String>.parameters(): String =
        takeIf(List<String>::isNotEmpty)?.joinToString(prefix = "<", postfix = ">") { it.identifier() }.orEmpty()
}

private fun GatewayProjection.address(): String = version?.let { "$name/v$it" } ?: name

private fun allocateTypeNames(types: List<TypeDescription>): Map<String, String> {
    val namesBySimple = types.groupBy { type -> type.name.substringAfterLast('.') }
    return types.associate { type ->
        val simple = type.name.substringAfterLast('.')
        type.name to if (namesBySimple.getValue(simple).size == 1) simple.identifier() else type.name.toTypeIdentifier()
    }
}

private fun mergeTypes(projection: GatewayProjection): List<TypeDescription> {
    val types = mutableMapOf<String, TypeDescription>()
    projection.services.forEach { service ->
        service.descriptor.description.types.forEach { type ->
            val existing = types[type.name]
            require(existing == null || existing == type) {
                "Incompatible gateway type descriptions for ${type.name}"
            }
            types[type.name] = type
        }
    }
    return types.values.sortedBy(TypeDescription::name)
}

private fun String.toPascalIdentifier(): String = split('-', '_', '.', '/')
    .filter(String::isNotEmpty)
    .joinToString("") { part -> part.replaceFirstChar(Char::uppercaseChar) }
    .identifier()

private fun String.toTypeIdentifier(): String = replace(Regex("[^A-Za-z0-9_$]"), "_").identifier()

private fun String.identifier(): String {
    val sanitized = replace(Regex("[^A-Za-z0-9_$]"), "_")
    val prefixed = if (sanitized.firstOrNull()?.let { it.isLetter() || it == '_' || it == '$' } == true) {
        sanitized
    } else {
        "_$sanitized"
    }
    return if (prefixed in TYPESCRIPT_RESERVED_WORDS) "_$prefixed" else prefixed
}

private fun String.propertyName(): String =
    if (TYPESCRIPT_IDENTIFIER.matches(this) && this !in TYPESCRIPT_RESERVED_WORDS) this else quoted()

private fun String.quoted(): String = buildString {
    append('"')
    this@quoted.forEach { character ->
        when (character) {
            '\\' -> append("\\\\")
            '"' -> append("\\\"")
            '\n' -> append("\\n")
            '\r' -> append("\\r")
            '\t' -> append("\\t")
            else -> append(character)
        }
    }
    append('"')
}

private val TYPESCRIPT_IDENTIFIER = Regex("[A-Za-z_$][A-Za-z0-9_$]*")
private val TYPESCRIPT_RESERVED_WORDS = setOf(
    "break", "case", "catch", "class", "const", "continue", "debugger", "default", "delete",
    "do", "else", "enum", "export", "extends", "false", "finally", "for", "function", "if",
    "import", "in", "instanceof", "new", "null", "return", "super", "switch", "this", "throw",
    "true", "try", "typeof", "var", "void", "while", "with", "yield",
)
