package ifx.service

/**
 * Build-time index of IFX contracts declared by one module.
 *
 * The index is generated by the shared build convention. Application and
 * contract code never needs to reference it directly.
 */
@Retention(AnnotationRetention.BINARY)
@Target(AnnotationTarget.CLASS)
annotation class IfxServiceIndex(vararg val services: String)
