import { build } from "esbuild";
import { copyFile, mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { gzipSync } from "node:zlib";

const here = dirname(fileURLToPath(import.meta.url));
const outputDirectory = resolve(here, "dist");
const bundledDirectory = resolve(
  here,
  "../../ifx.service-explorer/resources/ifx/service/explorer",
);
const nativeAssetsFile = resolve(
  here,
  "../../ifx.service-explorer/src@native/BundledServiceExplorerAssets.native.kt",
);
const outputJavaScript = resolve(outputDirectory, "test-ui.js");

await Promise.all([
  mkdir(outputDirectory, { recursive: true }),
  mkdir(bundledDirectory, { recursive: true }),
  mkdir(dirname(nativeAssetsFile), { recursive: true }),
]);
await Promise.all([
  copyFile(resolve(here, "index.html"), resolve(outputDirectory, "index.html")),
  copyFile(resolve(here, "index.html"), resolve(bundledDirectory, "index.html")),
  build({
    entryPoints: [resolve(here, "src/main.ts")],
    outfile: outputJavaScript,
    bundle: true,
    format: "iife",
    minify: true,
    platform: "browser",
    target: "es2022",
  }),
]);

const [html, javascript] = await Promise.all([
  readFile(resolve(here, "index.html")),
  readFile(outputJavaScript),
]);
const compressedJavaScript = gzipSync(javascript, { level: 9, mtime: 0 });

await Promise.all([
  writeFile(resolve(bundledDirectory, "test-ui.js.gz"), compressedJavaScript),
  writeFile(nativeAssetsFile, renderNativeAssets(html, compressedJavaScript)),
]);

function renderNativeAssets(html, compressedJavaScript) {
  return `// Generated by typescript/ifx-test-ui/build.mjs. Do not edit.
@file:OptIn(kotlin.io.encoding.ExperimentalEncodingApi::class)

package ifx.service.explorer

import kotlin.io.encoding.Base64

${renderByteArray("indexHtml", html)}

${renderByteArray("testUiJavaScriptGzip", compressedJavaScript)}

internal actual fun bundledServiceExplorerAsset(path: String): ByteArray = when (path) {
    "index.html" -> indexHtml
    "test-ui.js.gz" -> testUiJavaScriptGzip
    else -> error("Bundled Service Explorer asset does not exist: $path")
}
`;
}

function renderByteArray(name, content) {
  const chunks = content.toString("base64").match(/.{1,120}/g) ?? [];
  const encoded = chunks.map((chunk) => `            "${chunk}",`).join("\n");
  return `private val ${name}: ByteArray by lazy {
    Base64.decode(
        listOf(
${encoded}
        ).joinToString("")
    )
}`;
}
