import { build } from "esbuild";
import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const output = resolve(here, "dist/test-ui.js");
await build({
  entryPoints: [resolve(here, "src/main.ts")],
  outfile: output,
  bundle: true,
  format: "iife",
  minify: true,
  platform: "browser",
  target: "es2022",
});

const javascript = await readFile(output);
const encoded = javascript.toString("base64").match(/.{1,120}/g) ?? [];
const kotlin = `// Generated by typescript/ifx-test-ui/build.mjs. Do not edit.
package ifx.host

import kotlin.io.encoding.Base64
import kotlin.io.encoding.ExperimentalEncodingApi

internal object TestUiAssets {
    val html: String = """
        <!doctype html>
        <html lang="en">
          <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <meta name="color-scheme" content="light">
            <title>iFX Service Explorer</title>
          </head>
          <body>
            <div id="app"><p>Loading service explorer…</p></div>
            <script src="/ifx/test-ui.js"></script>
          </body>
        </html>
    """.trimIndent()

    @OptIn(ExperimentalEncodingApi::class)
    val javascript: String = Base64.decode(
        listOf(
${encoded.map((line) => `            "${line}",`).join("\n")}
        ).joinToString("")
    ).decodeToString()
}
`;
await writeFile(resolve(here, "../../ifx.host/src/TestUiAssets.kt"), kotlin);
