package ifx.rpc.typescript.ksp

import kotlin.test.Test
import kotlin.test.assertEquals

class TypeScriptRendererTest {
    @Test
    fun `renders operations and reachable wire types`() {
        val model = ServiceModel(
            name = "CatalogService",
            operations = listOf(
                OperationModel(
                    name = "find",
                    typeName = "Find",
                    parameterName = "criteria",
                    request = TypeRef.Named("example.Criteria"),
                    requestOptional = false,
                    response = TypeRef.Named("example.Product"),
                    interaction = Interaction.REQUEST_STREAM,
                ),
            ),
            declarations = listOf(
                TypeDeclaration.ObjectType(
                    qualifiedName = "example.Criteria",
                    typeParameters = emptyList(),
                    properties = listOf(
                        PropertyModel("ids", TypeRef.Nullable(TypeRef.ArrayType(TypeRef.StringType)), optional = true),
                    ),
                ),
                TypeDeclaration.SealedUnion(
                    qualifiedName = "example.Product",
                    typeParameters = emptyList(),
                    discriminator = "type",
                    variants = listOf(
                        SealedVariant("example.Car", TypeRef.Named("example.Car")),
                    ),
                ),
                TypeDeclaration.ObjectType(
                    qualifiedName = "example.Car",
                    typeParameters = emptyList(),
                    properties = listOf(PropertyModel("serial-number", TypeRef.NumberType, optional = false)),
                ),
            ),
        )

        assertEquals(
            """
            // Generated by ifx.rpc.typescript.ksp. Do not edit.

            export namespace CatalogService {
              export type FindRequest = Criteria;
              export type FindResponse = Product;
            }

            export interface CatalogService {
              find(criteria: CatalogService.FindRequest): AsyncIterable<CatalogService.FindResponse>;
            }

            export interface Criteria {
              readonly ids?: ReadonlyArray<string> | null;
            }

            export type Product =
              | ({ readonly type: "example.Car" } & Car);

            export interface Car {
              readonly "serial-number": number;
            }
            """.trimIndent() + "\n",
            TypeScriptRenderer().render(model),
        )
    }
}
