package ifx.rpc.typescript.ksp

import kotlin.test.Test
import kotlin.test.assertContains
import kotlin.test.assertEquals

class TypeScriptRendererTest {
    @Test
    fun `renders operations and reachable wire types`() {
        val model = ServiceModel(
            name = "CatalogService",
            address = "example.CatalogService",
            kind = ServiceKind.SERVICE,
            operations = listOf(
                OperationModel(
                    name = "find",
                    typeName = "Find",
                    route = "find(example.Criteria)",
                    parameterName = "criteria",
                    request = TypeRef.Named("example.Criteria"),
                    requestOptional = false,
                    response = TypeRef.Named("example.Product"),
                    interaction = Interaction.REQUEST_STREAM,
                ),
            ),
            declarations = listOf(
                TypeDeclaration.ObjectType(
                    qualifiedName = "example.Criteria",
                    typeParameters = emptyList(),
                    properties = listOf(
                        PropertyModel("ids", TypeRef.Nullable(TypeRef.ArrayType(TypeRef.StringType)), optional = true),
                    ),
                ),
                TypeDeclaration.SealedUnion(
                    qualifiedName = "example.Product",
                    typeParameters = emptyList(),
                    discriminator = "type",
                    variants = listOf(
                        SealedVariant("example.Car", TypeRef.Named("example.Car")),
                    ),
                ),
                TypeDeclaration.ObjectType(
                    qualifiedName = "example.Car",
                    typeParameters = emptyList(),
                    properties = listOf(PropertyModel("serial-number", TypeRef.NumberType, optional = false)),
                ),
            ),
        )

        assertEquals(
            """
            // Generated by ifx.rpc.typescript.ksp. Do not edit.

            import {
              type IfxBinding as __IfxBinding,
              type IfxServiceDescription as __IfxServiceDescription,
            } from "@ifx/rpc-sdk";

            export const CatalogServiceAddress = "example.CatalogService";

            export const CatalogServiceDescription = {
              name: "CatalogService",
              address: CatalogServiceAddress,
              kind: "service",
              operations: [
                {
                  name: "find",
                  route: "find(example.Criteria)",
                  parameterName: "criteria",
                  request: { type: "named", name: "example.Criteria", arguments: [] },
                  response: { type: "named", name: "example.Product", arguments: [] },
                  interaction: "requestStream",
                },
              ],
              types: [
                { type: "object", name: "example.Criteria", typeParameters: [], properties: [{ name: "ids", type: { type: "nullable", value: { type: "array", element: { type: "string" } } }, optional: true }] },
                { type: "sealedUnion", name: "example.Product", typeParameters: [], discriminator: "type", variants: [{ serialName: "example.Car", type: { type: "named", name: "example.Car", arguments: [] } }] },
                { type: "object", name: "example.Car", typeParameters: [], properties: [{ name: "serial-number", type: { type: "number" }, optional: false }] },
              ],
            } as const satisfies __IfxServiceDescription;

            export namespace CatalogService {
              export type FindRequest = Criteria;
              export type FindResponse = Product;
            }

            export interface CatalogService {
              find(criteria: CatalogService.FindRequest): AsyncIterable<CatalogService.FindResponse>;
            }

            export class CatalogServiceSdk implements CatalogService {
              static readonly address = CatalogServiceAddress;

              constructor(private readonly binding: __IfxBinding) {}

              find(criteria: CatalogService.FindRequest): AsyncIterable<CatalogService.FindResponse> {
                return this.binding.requestStream<CatalogService.FindResponse>("find(example.Criteria)", criteria);
              }

              close(): void {
                this.binding.close();
              }
            }

            export interface Criteria {
              readonly ids?: ReadonlyArray<string> | null;
            }

            export type Product =
              | ({ readonly type: "example.Car" } & Car);

            export interface Car {
              readonly "serial-number": number;
            }
            """.trimIndent() + "\n",
            TypeScriptRenderer().render(model),
        )
    }

    @Test
    fun `renders Unit request-response separately from explicit fire-and-forget`() {
        val model = ServiceModel(
            name = "CommandService",
            address = "example.CommandService",
            kind = ServiceKind.SERVICE,
            operations = listOf(
                OperationModel(
                    name = "store",
                    typeName = "Store",
                    route = "store(example.Command)",
                    parameterName = "command",
                    request = TypeRef.Named("example.Command"),
                    requestOptional = false,
                    response = TypeRef.VoidType,
                    interaction = Interaction.REQUEST_RESPONSE,
                ),
                OperationModel(
                    name = "notify",
                    typeName = "Notify",
                    route = "notify(example.Command)",
                    parameterName = "command",
                    request = TypeRef.Named("example.Command"),
                    requestOptional = false,
                    response = TypeRef.VoidType,
                    interaction = Interaction.FIRE_AND_FORGET,
                ),
            ),
            declarations = listOf(
                TypeDeclaration.ObjectType(
                    qualifiedName = "example.Command",
                    typeParameters = emptyList(),
                    properties = emptyList(),
                ),
            ),
        )

        val source = TypeScriptRenderer().render(model)

        assertContains(source, "interaction: \"requestResponse\"")
        assertContains(source, "interaction: \"fireAndForget\"")
        assertContains(source, "  async store(command: CommandService.StoreRequest): Promise<CommandService.StoreResponse> {")
        assertContains(source, "    await this.binding.requestResponse<CommandService.StoreResponse>(\"store(example.Command)\", command);")
        assertContains(source, "  notify(command: CommandService.NotifyRequest): Promise<CommandService.NotifyResponse> {")
        assertContains(source, "    return this.binding.fireAndForget(\"notify(example.Command)\", command);")
    }
}
