package ifx.rpc.typescript.ksp

import kotlin.test.Test
import kotlin.test.assertEquals

class TypeScriptRendererTest {
    @Test
    fun `renders operations and reachable wire types`() {
        val model = ServiceModel(
            name = "CatalogService",
            address = "example.CatalogService",
            operations = listOf(
                OperationModel(
                    name = "find",
                    typeName = "Find",
                    route = "find(example.Criteria)",
                    parameterName = "criteria",
                    request = TypeRef.Named("example.Criteria"),
                    requestOptional = false,
                    response = TypeRef.Named("example.Product"),
                    interaction = Interaction.REQUEST_STREAM,
                ),
            ),
            declarations = listOf(
                TypeDeclaration.ObjectType(
                    qualifiedName = "example.Criteria",
                    typeParameters = emptyList(),
                    properties = listOf(
                        PropertyModel("ids", TypeRef.Nullable(TypeRef.ArrayType(TypeRef.StringType)), optional = true),
                    ),
                ),
                TypeDeclaration.SealedUnion(
                    qualifiedName = "example.Product",
                    typeParameters = emptyList(),
                    discriminator = "type",
                    variants = listOf(
                        SealedVariant("example.Car", TypeRef.Named("example.Car")),
                    ),
                ),
                TypeDeclaration.ObjectType(
                    qualifiedName = "example.Car",
                    typeParameters = emptyList(),
                    properties = listOf(PropertyModel("serial-number", TypeRef.NumberType, optional = false)),
                ),
            ),
        )

        assertEquals(
            """
            // Generated by ifx.rpc.typescript.ksp. Do not edit.

            import {
              RSocketBinding as __IfxRSocketBinding,
              type IfxBinding as __IfxBinding,
              type RSocketBindingOptions as __IfxRSocketBindingOptions,
            } from "@ifx/rpc-client";

            export const CatalogServiceAddress = "example.CatalogService";

            export namespace CatalogService {
              export type FindRequest = Criteria;
              export type FindResponse = Product;
            }

            export interface CatalogService {
              find(criteria: CatalogService.FindRequest): AsyncIterable<CatalogService.FindResponse>;
            }

            export class CatalogServiceClient implements CatalogService {
              static async connect(
                baseUrl: string,
                options: Omit<__IfxRSocketBindingOptions, "url"> = {},
              ): Promise<CatalogServiceClient> {
                const url = __IfxRSocketBinding.serviceUrl(baseUrl, CatalogServiceAddress);
                return new CatalogServiceClient(await __IfxRSocketBinding.connect({ ...options, url }));
              }

              constructor(private readonly binding: __IfxBinding) {}

              find(criteria: CatalogService.FindRequest): AsyncIterable<CatalogService.FindResponse> {
                return this.binding.requestStream<CatalogService.FindResponse>("find(example.Criteria)", criteria);
              }

              close(): void {
                this.binding.close();
              }
            }

            export interface Criteria {
              readonly ids?: ReadonlyArray<string> | null;
            }

            export type Product =
              | ({ readonly type: "example.Car" } & Car);

            export interface Car {
              readonly "serial-number": number;
            }
            """.trimIndent() + "\n",
            TypeScriptRenderer().render(model),
        )
    }
}
