package ifx.protocol.contract

import ifx.service.IService
import kotlin.reflect.KClass

/** Compile-time description of an [IService] contract. Generated by ifx-rpc-ksp. */
interface ServiceDescriptor<T : IService> {
    val contract: KClass<T>
    val address: String
    fun createClient(binding: IBinding): T
    fun bind(instance: T): IBinding
}

class ServiceRegistry(descriptors: Iterable<ServiceDescriptor<out IService>>) {
    private val descriptors = descriptors.associateBy { it.contract }

    @Suppress("UNCHECKED_CAST")
    fun <T : IService> descriptor(contract: KClass<T>): ServiceDescriptor<T> =
        descriptors[contract] as? ServiceDescriptor<T>
            ?: error("No generated service descriptor registered for ${contract.simpleName}")
}
