package ifx.protocol.contract

import ifx.service.IService
import kotlin.reflect.KClass

/** Compile-time description of an [IService] contract. Generated by ifx-rpc-ksp. */
interface ServiceDescriptor<T : IService> {
    val contract: KClass<T>
    val address: String
    fun createClient(binding: IBinding): T
    fun bind(instance: T): IBinding
}
