package ifx.protocol.contract

import ifx.service.IService
import kotlin.reflect.KClass

/** Compile-time description of an [IService] contract. Generated by ifx.subsystem.ksp. */
interface ServiceDescriptor<T : IService> {
    val contract: KClass<T>
    val address: String
    val description: ServiceDescription
    fun createClient(binding: IBinding): T
    fun bind(instance: T): IBinding
}

fun <T : IService> serviceAddressOf(contract: KClass<T>): String =
    contract.qualifiedName ?: error("IFX service contracts must have a qualified name")

inline fun <reified T : IService> serviceAddressOf(): String = serviceAddressOf(T::class)
